config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'profiles#show'
  resource :profile, only: %i[show edit update]

  namespace :admin do
    resources :users do
      collection do
        get :export
        get :welcome_email
      end
      member do
        get :send_email
        post :send_welcome_sms
      end
    end

    resource :statistics, only: :show
    resources :hash_tags, only: %i[index show]
    resources :categories
    resources :interests
    resources :sources, only: %i[index new create destroy]
    resources :facebook_posts, only: :index do
      member do
        post :send_to_facebook
      end
    end
  end

  namespace :auth do
    resource :facebook, only: :show do
      member do
        get :callback
      end
    end
  end

  namespace :api do
    resources :users, only: %i[show index create update destroy] do
      resources :interests, only: [:index]
    end
  end
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :organization
  has_many :tweets_sources
  has_many :tweets, through: :tweets_sources

  validates :name, presence: true, format: { with: /\A#\w*\z/ }

  scope :in_organization, ->(organization) { where(organization: organization) }
end

app/controllers/admin/sources_controller.rb
class Admin::SourcesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :user_not_found

  def index
    sources = Source.in_organization(current_organization)
    authorize sources
    render :index, locals: { sources: sources }
  end

  def new
    source = Source.new
    authorize source
    render :new, locals: { source: source }
  end

  def create
    source = Source.new(source_params)
    authorize source
    source.organization = current_user.organization
    if source.save
      redirect_to admin_sources_path
    else
      render :new, locals: { source: source }
    end
  end

  def destroy
    source = Source.in_organization(current_organization).find(params[:id])
    authorize source
    source.destroy
    redirect_to admin_sources_path
  end

  private

  def source_params
    params.require(:source).permit(:name)
  end

  def user_not_found
    redirect_to admin_sources_path
  end
end

app/views/admin/sources/_form.html.haml
= simple_form_for [:admin, source], html: { class: 'form-horizontal' } do |f|
  = f.input :name

  = f.button :submit, class: 'btn-primary'

app/views/admin/sources/index.html.haml
- model_class = Source
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - sources.each do |source|
      - cache source do
        %tr
          %td= source.name
          %td
            = link_to t('.destroy', default: t("helpers.links.destroy")), admin_source_path(source), method: :delete,
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-xs btn-danger', id: "source_delete_#{source.id}"

= link_to t('.new', default: t("helpers.links.new")), new_admin_source_path, class: 'btn btn-primary', id: 'new_source'
= link_to 'Refresh Facebook Access Token', auth_facebook_path, class: 'btn btn-primary'

app/views/admin/sources/new.html.haml
- model_class = Source

.page-header
  %h1=t '.title', deault:[:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize

= render partial: "form", locals: { source: source }

= link_to t('.cancel', default: t("helpers.links.cancel")), admin_sources_path, class: 'btn btn-default'