config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'profiles#show'
  resource :profile, only: %i[show edit update]

  namespace :admin do
    resources :users do
      collection do
        get :export
        get :welcome_email
      end
      member do
        get :send_email
        post :send_welcome_sms
      end
    end

    resource :statistics, only: :show
    resources :hash_tags, only: %i[index show]
    resources :categories
    resources :interests
    resources :sources, only: %i[index new create destroy]
    resources :facebook_posts, only: :index do
      member do
        post :send_to_facebook
      end
    end
  end

  namespace :auth do
    resource :facebook, only: :show do
      member do
        get :callback
      end
    end
  end

  namespace :api do
    resources :users, only: %i[show index create update destroy] do
      resources :interests, only: [:index]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :interests
  belongs_to :organization
  has_many :users, through: :interests

  validates :name, presence: true

  scope :in_organization, ->(organization) { where(organization: organization) }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!

  def show
    category = Category.in_organization(current_organization).find(params[:id])
    authorize category
    render :show, locals: { category: category }
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_categories_path
  end

  def index
    categories = Category.in_organization(current_organization)
    users_count_per_category = UsersCountPerCategory.result_for(organization: current_organization)
    authorize categories
    render :index, locals: { categories: categories, users_count_per_category: users_count_per_category }
  end

  def new
    category = Category.new
    authorize category
    render :new, locals: { category: category }
  end

  def create
    category = Category.new(category_params)
    authorize category

    if category.save
      redirect_to admin_category_path(category)
    else
      render :new
    end
  end

  def edit
    category = Category.in_organization(current_organization).find(params[:id])
    authorize category
    render :edit, locals: { category: category }
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_categories_path
  end

  def update
    category = Category.in_organization(current_organization).find(params[:id])
    authorize category

    if category.update(category_params)
      redirect_to admin_category_path(category)
    else
      render :edit
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_categories_path
  end

  def destroy
    category = Category.in_organization(current_organization).find(params[:id])
    authorize category
    category.destroy
    redirect_to admin_categories_path
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/admin/categories/_form.html.haml
= simple_form_for [:admin, category], html: { class: 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.button :submit, class: 'btn-primary'

app/views/admin/categories/edit.html.haml
- model_class = Category

.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize

= render "admin/categories/form", locals: { category: category }

= link_to t('.cancel', default: t("helpers.links.cancel")), admin_categories_path, class: 'btn btn-default'

app/views/admin/categories/index.html.haml
- model_class = Category
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize

.users-by-category{ "data-category-stats" => users_count_per_category.to_json }

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - categories.each do |category|
      %tr
        %td= category.name
        %td
          = link_to t('.show', default: t("helpers.links.show")), admin_category_path(category), class: 'btn btn-default btn-xs'
          = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_category_path(category), class: 'btn btn-default btn-xs'
          = link_to t('.destroy', default: t("helpers.links.destroy")), admin_category_path(category), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs btn-danger'

= link_to t('.new', default: t("helpers.links.new")), new_admin_category_path, class: 'btn btn-primary'

app/views/admin/categories/new.html.haml
- model_class = Category

.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize

= render partial: "form", locals: { category: category }

= link_to t('.cancel', default: t("helpers.links.cancel")), admin_categories_path, class: 'btn btn-default'

app/views/admin/categories/show.html.haml
- model_class = Category
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = category.name


= link_to t('.back', default: t("helpers.links.back")), admin_categories_path, class: 'btn btn-default'
= link_to t('.edit', default: t("helpers.links.edit")), edit_admin_category_path(category), class: 'btn btn-default'
= link_to t('.destroy', default: t("helpers.links.destroy")), admin_category_path(category), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'