config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'profiles#show'
  resource :profile, only: %i[show edit update]

  namespace :admin do
    resources :users do
      collection do
        get :export
        get :welcome_email
      end
      member do
        get :send_email
        post :send_welcome_sms
      end
    end

    resource :statistics, only: :show
    resources :hash_tags, only: %i[index show]
    resources :categories
    resources :interests
    resources :sources, only: %i[index new create destroy]
    resources :facebook_posts, only: :index do
      member do
        post :send_to_facebook
      end
    end
  end

  namespace :auth do
    resource :facebook, only: :show do
      member do
        get :callback
      end
    end
  end

  namespace :api do
    resources :users, only: %i[show index create update destroy] do
      resources :interests, only: [:index]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch

  USERS_PER_PAGE = 30

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :organization
  has_many :interests, through: :users_interests
  has_many :users_interests
  has_many :categories, through: :interests

  validates :first_name, :last_name, :email, :age, presence: true
  validate :validate_phone_number

  scope :in_organization, ->(organization) { where(organization: organization) }
  scope :with_age_between, ->(age_range) { where(age: age_range) }
  scope :with_gender, ->(gender) { where(gender: gender) }

  delegate :facebook_auth_expired?, to: :organization

  pg_search_scope :search_by, against: %i[first_name last_name email age gender], using: { tsearch: { any_word: true } }

  paginates_per USERS_PER_PAGE

  def self.per_page
    20
  end

  def self.pages(per_page = self.per_page)
    (count / per_page.to_f).ceil
  end

  def self.paginate(page: 1, per_page: self.per_page)
    page_offset = (page - 1) * per_page
    limit(per_page).offset(page_offset)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def interests_list
    interests.pluck(:name).join(', ')
  end

  def values_to_export
    [first_name, last_name, email, gender, age, interests.map(&:name)].flatten!
  end

  def json_web_token
    ::JsonWebToken.encode(id: id)
  end

  def validate_phone_number
    if mobile_phone.present?
      unless TwilioWrapper.new.valid_phone_number?(mobile_phone)
        errors.add(:mobile_phone, 'Given mobile phone is invalid')
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :user_not_found

  def show
    user = User.in_organization(current_organization).find(params[:id])
    authorize user
    render :show, locals: { user: user }
  end

  def index
    users = search_users.page params[:page]
    users_by_age = UsersByAge.result_for(organization: current_organization)
    authorize users
    render :index, locals: { users: users, users_by_age: users_by_age }
  end

  def new
    user = User.new
    authorize user
    render :new, locals: { user: user }
  end

  def create
    user = User.new(user_params)
    user.password = user.password_confirmation = Devise.friendly_token.first(8)
    user.organization = current_user.organization
    authorize user

    if user.save
      flash[:notice] = t('admin.notices.user_created')
      user.send_reset_password_instructions
      broadcast_user
      Broadcast::UpdateCategoriesStats.call(organization: current_organization)
      redirect_to admin_user_path(user)
    else
      render :new, locals: { user: user }
    end
  end

  def edit
    user = User.in_organization(current_organization).find(params[:id])
    authorize user
    render :edit, locals: { user: user }
  end

  def update
    user = User.in_organization(current_organization).find(params[:id])
    authorize user
    if user.update(user_params)
      Broadcast::UpdateCategoriesStats.call(organization: current_organization)
      flash[:notice] = t('admin.notices.user_updated')
      redirect_to admin_user_path(user)
    else
      render :edit, locals: { user: user }
    end
  end

  def destroy
    user = User.in_organization(current_organization).find(params[:id])
    authorize user
    user.destroy
    flash[:notice] = t('admin.notices.user_deleted')
    redirect_to admin_users_path
  end

  def export
    users = User.in_organization(current_organization)
    respond_to do |format|
      format.csv do
        send_data ExportUsersAsCSV.call(users),
                  filename: "users_export-#{Date.today}.csv"
      end
    end
  end

  def send_email
    user = User.in_organization(current_organization).find(params[:id])
    authorize user
    SendEmail.call(current_user, user)
    respond_to do |format|
      format.js
    end
  end

  def welcome_email
    authorize current_user
    SendWelcomeEmail.call(current_user)
    respond_to do |format|
      format.js
    end
  end

  def send_welcome_sms
    user = User.in_organization(current_organization).find(params[:id])
    authorize user
    UserNotifications::SmsSender.call(to: user.mobile_phone, message: "Welcome #{user.full_name}!")
    respond_to do |format|
      format.js
    end
  end

private

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password_confirmation)
      params[:user].delete(:password)
    end

    params.require(:user).permit(
      :email, :first_name, :last_name, :age, :gender, :mobile_phone, :admin, :password,
      :password_confirmation, interest_ids: []
    )
  end

  def search_params
    params.fetch(:search, {}).fetch(:text, nil)
  end

  def search_users
    users = User.in_organization(current_organization).order(:email)
    search_params.present? ? users.search_by(search_params) : users
  end

  def broadcast_user
    ActionCable.server.broadcast(
      'users',
      users_by_age: UsersByAge.result_for(organization: current_organization)
    )
  end

  def user_not_found
    redirect_to admin_users_path
  end

  helper_method def gender_list
    %w[male female]
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  def index
    users = User.in_organization(current_organization).order(:id).paginate(page: page, per_page: per_page)

    authorize users

    render json: UsersSerializer.new(users, page, per_page).serialize
  end

  def show
    user = User.in_organization(current_organization).find(params[:id])

    authorize user

    render json: UserSerializer.new(user).serialize
  end

  def create
    user = User.new(user_params)
    user.password = user.password_confirmation = Devise.friendly_token.first(8)
    user.organization = current_organization

    authorize user

    if user.save
      user.send_reset_password_instructions
      render json: UserSerializer.new(user).serialize, status: :created
    else
      render json: { errors: user.errors.messages }, status: :bad_request
    end
  end

  def update
    user = User.in_organization(current_organization).find(params[:id])

    authorize user

    if user.update(user_params)
      render json: UserSerializer.new(user).serialize
    else
      render json: { errors: user.errors.messages }, status: :bad_request
    end
  end

  def destroy
    user = User.in_organization(current_organization).find(params[:id])

    authorize user

    if user.delete
      render json: {}, status: :no_content
    end
  end

  private

  def user_params
    params.require(:data).require(:attributes).permit(
      :email, :first_name, :last_name, :age, :gender, :admin, interest_ids: []
    )
  end

  def page
    params.fetch(:page, 1).to_i
  end

  def per_page
    params.fetch(:per_page, User.per_page).to_i
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email first_name last_name password password_confirmation])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, user], html: { class: 'form-horizontal', id: 'form' } do |f|
  = f.input :email

  = f.input :first_name

  = f.input :last_name

  = f.input :gender, collection: gender_list, include_blank: false

  = f.input :age, collection: 1..120

  = f.input :mobile_phone

  = f.input :password

  = f.input :password_confirmation

  = f.input :admin, as: :boolean, checked_value: true, unchecked_value: false

  %h3 Interests

  = f.association :interests, include_blank: false

  = f.button :submit, class: 'btn-primary'

app/views/admin/users/_search_postgres.html.haml
.container
  .row
    .span12
      = simple_form_for :search, url: admin_users_path, method: :get, html: { class: 'form-search form-horizontal' } do |f|

        = f.input :text, placeholder: "Search"

        = f.submit 'Search', class: 'btn btn-default', id: 'user_search_button'

app/views/admin/users/edit.html.haml
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: User.model_name.human.titleize

= render "admin/users/form", { user: user }

= link_to t('.cancel', default: t("helpers.links.cancel")), admin_user_path(user), class: 'btn btn-default'

app/views/admin/users/index.html.haml
.page-header
  %h1=t '.title', default: User.model_name.human.pluralize.titleize
  %p
    =t 'admin.interest_statistic'
    = FemaleHealthInterestsCount.result_for(organization: current_organization)

.users-by-age{ "data-age-stats" => users_by_age.to_json }

= render partial: 'search_postgres', locals: { users: users }

= link_to ' Welcome email',
    welcome_email_admin_users_path, remote: true, class: 'btn btn-success glyphicon glyphicon-envelope', id: "send_welcome_email"

%p
  = paginate users
%p
  = page_entries_info users
%table.table.table-striped
  %thead
    %tr
      %th= User.human_attribute_name(:email)

      %th= User.human_attribute_name(:first_name)

      %th= User.human_attribute_name(:last_name)

      %th= User.human_attribute_name(:mobile_phone)

      %th= User.human_attribute_name(:gender)

      %th= User.human_attribute_name(:age)

      %th= User.human_attribute_name(:interests)

      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - users.each do |user|
      %tr.user_row
        %td= user.email

        %td= user.first_name

        %td= user.last_name

        %td= user.mobile_phone

        %td= user.gender

        %td= user.age

        %td= user.interests_list

        %td
          = link_to t('.show', default: t("helpers.links.show")),
              admin_user_path(user), class: 'btn btn-default btn-xs', id: "user_show_#{user.id}"

          = link_to t('.edit', defaul: t("helpers.links.edit")),
              edit_admin_user_path(user), class: 'btn btn-default btn-xs', id: "user_edit_#{user.id}"

          - if current_user.id != user.id
            = link_to '',
              admin_user_path(user), method: :delete,
              data: { confirm: t('.confirm', default: t("helpers.links.confirm",
                      default: 'Are you sure?')) }, class: 'btn btn-xs btn-danger glyphicon glyphicon-trash', id: "user_delete_#{user.id}"

          %a(href='#' class='btn btn-success btn-xs glyphicon glyphicon-envelope send-user-email' data-user-id="#{user.id}")

          %a(href='#' class='btn btn-success btn-xs glyphicon glyphicon-phone send-user-sms' data-user-id="#{user.id}")

= link_to t('.new', default: t("helpers.links.new")), new_admin_user_path,
    class: 'btn btn-primary', id: 'new_user'

= link_to "Export to CSV", export_admin_users_path({ format: :csv }),
    class: 'btn btn-success', id: 'export_csv'

app/views/admin/users/new.html.haml
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: User.model_name.human.titleize

= render partial: "form", locals: { user: user }

= link_to t('.cancel', default: t("helpers.links.cancel")), admin_users_path, class: 'btn btn-default'

app/views/admin/users/show.html.haml
.page-header
  %h1=t '.title', default: user.full_name

%p
  %strong #{User.human_attribute_name(:email)}:
  %br
  = user.email

%p
  %strong #{User.human_attribute_name(:first_name)}:
  %br
  = user.first_name

%p
  %strong #{User.human_attribute_name(:last_name)}:
  %br
  = user.last_name

- if user.gender
  %p
    %strong #{User.human_attribute_name(:gender)}:
    %br
    = user.gender

- if user.age
  %p
    %strong #{User.human_attribute_name(:age)}:
    %br
    = user.age

- if user.mobile_phone
  %p
    %strong #{User.human_attribute_name(:mobile_phone)}:
    %br
    = user.mobile_phone

- if user.interests.any?
  %h4 Interests:

  %table.table.table-striped
    %thead
      %tr
        %th= Interest.human_attribute_name(:name)

        %th= Interest.human_attribute_name(:category)
    %tbody
      - user.interests.each do |interest|
        %tr
          %td= interest.name

          %td= interest.category_name

= link_to t('.back', default: t("helpers.links.back")), admin_users_path, class: 'btn btn-danger'
= link_to t('.edit', default: t("helpers.links.edit")), edit_admin_user_path(user), class: 'btn btn-success'