config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'profiles#show'
  resource :profile, only: %i[show edit update]

  namespace :admin do
    resources :users do
      collection do
        get :export
        get :welcome_email
      end
      member do
        get :send_email
        post :send_welcome_sms
      end
    end

    resource :statistics, only: :show
    resources :hash_tags, only: %i[index show]
    resources :categories
    resources :interests
    resources :sources, only: %i[index new create destroy]
    resources :facebook_posts, only: :index do
      member do
        post :send_to_facebook
      end
    end
  end

  namespace :auth do
    resource :facebook, only: :show do
      member do
        get :callback
      end
    end
  end

  namespace :api do
    resources :users, only: %i[show index create update destroy] do
      resources :interests, only: [:index]
    end
  end
end

app/views/layouts/_navbar.html.haml
= nav_bar fixed: :top, brand: current_user.organization.name do
  = menu_group do
    = menu_item "Profile", root_path
    - if current_user.admin
      = drop_down "Admin" do
        = menu_item "Admin Panel", admin_users_path, id: 'admin_users_index_link'
        = menu_item "Categories", admin_categories_path, id: 'admin_categories_index_link'
        = menu_item "Interests", admin_interests_path, id: 'admin_interests_index_link'
        = menu_item "Sources", admin_sources_path, id: 'admin_sources_index_link'
        = menu_item "Statistics", admin_statistics_path, id: 'admin_statistics_show_link'
        = menu_item "Hash Tags", admin_hash_tags_path, id: 'admin_hash_tags_index_link'
        = menu_item "Facebook posts", admin_facebook_posts_path, id: 'admin_facebook_posts_link'
  = menu_group pull: :right do
    = menu_item "Log Out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Web App
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    - if current_user
      = render 'layouts/navbar'
    .container.main-container
      - if current_user
        - if current_user.admin? && current_user.facebook_auth_expired?
          .alert.alert-warning
            %p Please refresh Facebook Access Token.
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      = yield